In [1]:
# Create a function so that the columns of the output matrix are powers of the input vector. 
# Let list1 be the values provided and increasing be the boolean supplied. Default the boolean to false

import numpy as np
def vander_mat(list1,increasing='False'):
    n=np.array(list1)
    l=n.size
    if increasing=='True':
        b=np.mat([n**i for i in range(l)])
    else:
        b=np.mat([n**i for i in range(l-1,-1,-1)])

# Return the transpose of the matrix created above since that is the required Vandermonde matrix. 
    return(b.transpose())

# Print the matrix for the values given with Increasing as True
print(vander_mat([3,5,7,9],'True'))

# Print the matrix for the values given with Increasing as False
print(vander_mat([3,5,7,9],'False'))

# Print the matrix for the values given with Increasing value not provided. It should default to False. 
print(vander_mat([3,5,7,9]))

[[  1   3   9  27]
 [  1   5  25 125]
 [  1   7  49 343]
 [  1   9  81 729]]
[[ 27   9   3   1]
 [125  25   5   1]
 [343  49   7   1]
 [729  81   9   1]]
[[ 27   9   3   1]
 [125  25   5   1]
 [343  49   7   1]
 [729  81   9   1]]


In [2]:
#Validate the answers with the numpy function vander.
print(np.vander([3,5,7,9],increasing=True))
print(np.vander([3,5,7,9],increasing=False))
print(np.vander([3,5,7,9]))

[[  1   3   9  27]
 [  1   5  25 125]
 [  1   7  49 343]
 [  1   9  81 729]]
[[ 27   9   3   1]
 [125  25   5   1]
 [343  49   7   1]
 [729  81   9   1]]
[[ 27   9   3   1]
 [125  25   5   1]
 [343  49   7   1]
 [729  81   9   1]]
